const today = new Date().toISOString().slice(0, 10);
const promptStrictness = [
  "Use only the provided input data.",
  "Do not invent locations, prices, times, documents, or business facts.",
  "If a value is missing or ambiguous, explicitly say what is missing.",
  "Keep all numbers consistent with the input.",
  "Return one short summary and 2-3 short bullet points.",
  "Answer in the requested language only.",
].join(" ");

export const seedUsers = [
  {
    id: "user-admin",
    username: "admin",
    email: "admin@west.local",
    name: "West Admin",
    role: "admin",
    password: "1234",
    company: "WEST Platform",
    capabilities: ["manage_all", "view_dashboard", "manage_users"],
    createdAt: "2026-06-11T00:00:00.000Z",
  },
  {
    id: "user-shipper",
    username: "shipper",
    email: "shipper@west.local",
    name: "Aigerim Shipper",
    role: "shipper",
    password: "1234",
    company: "North Gate Export",
    capabilities: ["create_orders", "choose_driver", "book_port", "track_cargo"],
    createdAt: "2026-06-11T00:00:00.000Z",
  },
  {
    id: "user-carrier",
    username: "carrier",
    email: "carrier@west.local",
    name: "Caspian Carrier",
    role: "carrier",
    password: "1234",
    company: "Caspian Fleet",
    capabilities: ["browse_loads", "accept_loads", "book_port", "view_routes"],
    createdAt: "2026-06-11T00:00:00.000Z",
  },
];

export const seedDrivers = [
  {
    id: "driver-aktau-01",
    name: "Aidar Zhumabaev",
    transportType: "truck",
    rating: 4.9,
    score: 96,
    trips: 312,
    eco: 88,
    delays: 2,
    cancels: 0,
    homeBase: "Aktau",
    routes: ["Aktau", "Atyrau", "Beyneu"],
    hourlyRate: 6200,
    pricePerKm: 430,
    available: true,
    status: "online",
  },
  {
    id: "driver-caspian-02",
    name: "Caspian Lines",
    transportType: "ship",
    rating: 4.7,
    score: 91,
    trips: 1280,
    eco: 72,
    delays: 14,
    cancels: 2,
    homeBase: "Kuryk",
    routes: ["Kuryk", "Baku", "Turkmenbashi"],
    hourlyRate: 9800,
    pricePerKm: 520,
    available: true,
    status: "busy",
  },
  {
    id: "driver-mangistau-03",
    name: "Mangystau Logistics",
    transportType: "truck",
    rating: 4.4,
    score: 78,
    trips: 540,
    eco: 41,
    delays: 22,
    cancels: 5,
    homeBase: "Beineu",
    routes: ["Beineu", "Aktau", "Russia Border"],
    hourlyRate: 4100,
    pricePerKm: 300,
    available: false,
    status: "offline",
  },
  {
    id: "driver-transcaspian-04",
    name: "TransCaspian Rail",
    transportType: "rail",
    rating: 4.8,
    score: 93,
    trips: 860,
    eco: 95,
    delays: 6,
    cancels: 1,
    homeBase: "Beyneu",
    routes: ["Beyneu", "Aktau", "Almaty"],
    hourlyRate: 8700,
    pricePerKm: 470,
    available: true,
    status: "online",
  },
  {
    id: "driver-nurlan-05",
    name: "Nurlan Serikov",
    transportType: "truck",
    rating: 4.2,
    score: 72,
    trips: 145,
    eco: 30,
    delays: 9,
    cancels: 3,
    homeBase: "Aktau",
    routes: ["Aktau", "Kuryk", "Shetpe"],
    hourlyRate: 3600,
    pricePerKm: 260,
    available: true,
    status: "online",
  },
  {
    id: "driver-azership-06",
    name: "AzerShip Co.",
    transportType: "ship",
    rating: 4.6,
    score: 88,
    trips: 720,
    eco: 68,
    delays: 11,
    cancels: 2,
    homeBase: "Baku",
    routes: ["Baku", "Aktau", "Turkmenbashi"],
    hourlyRate: 9100,
    pricePerKm: 490,
    available: true,
    status: "online",
  },
];

export const seedFreights = [
  {
    id: "freight-01",
    from: "Aktau",
    to: "Atyrau",
    weight: 18,
    type: "Petrochemicals",
    price: 420000,
    shipper: "KazOil LLP",
    rating: 4.8,
    eco: true,
    distance: 510,
    transportType: "truck",
    status: "open",
    priority: 96,
    deadline: "2026-06-12",
  },
  {
    id: "freight-02",
    from: "Kuryk",
    to: "Baku",
    weight: 24,
    type: "Container",
    price: 380000,
    shipper: "Caspian Lines",
    rating: 4.6,
    eco: false,
    distance: 380,
    transportType: "ship",
    status: "open",
    priority: 88,
    deadline: "2026-06-13",
  },
  {
    id: "freight-03",
    from: "Zhanaozen",
    to: "Aktau",
    weight: 12,
    type: "Construction",
    price: 180000,
    shipper: "Mangistau Build",
    rating: 4.2,
    eco: true,
    distance: 150,
    transportType: "truck",
    status: "open",
    priority: 75,
    deadline: "2026-06-11",
  },
  {
    id: "freight-04",
    from: "Aktau Port",
    to: "Almaty",
    weight: 22,
    type: "Refrigerated",
    price: 920000,
    shipper: "FreshLine",
    rating: 4.9,
    eco: true,
    distance: 2600,
    transportType: "truck",
    status: "open",
    priority: 98,
    deadline: "2026-06-14",
  },
  {
    id: "freight-05",
    from: "Beyneu",
    to: "Shetpe",
    weight: 8,
    type: "General",
    price: 95000,
    shipper: "RegionTrans",
    rating: 4.4,
    eco: false,
    distance: 220,
    transportType: "truck",
    status: "open",
    priority: 62,
    deadline: "2026-06-11",
  },
  {
    id: "freight-06",
    from: "Turkmenbashi",
    to: "Kuryk",
    weight: 30,
    type: "Sea container",
    price: 540000,
    shipper: "TransCaspian",
    rating: 4.7,
    eco: true,
    distance: 320,
    transportType: "ship",
    status: "open",
    priority: 90,
    deadline: "2026-06-13",
  },
];

export const seedPorts = [
  {
    id: "aktau",
    name: "Aktau",
    city: "Aktau",
    kind: "sea",
    load: 86,
    capacityPerDay: 120,
    timezone: "Asia/Qyzylorda",
    latitude: 43.653,
    longitude: 51.185,
  },
  {
    id: "kuryk",
    name: "Kuryk",
    city: "Kuryk",
    kind: "sea",
    load: 38,
    capacityPerDay: 90,
    timezone: "Asia/Qyzylorda",
    latitude: 43.185,
    longitude: 51.675,
  },
  {
    id: "baku",
    name: "Baku",
    city: "Baku",
    kind: "sea",
    load: 62,
    capacityPerDay: 150,
    timezone: "Asia/Baku",
    latitude: 40.409,
    longitude: 49.867,
  },
  {
    id: "turkmenbashi",
    name: "Turkmenbashi",
    city: "Turkmenbashi",
    kind: "sea",
    load: 28,
    capacityPerDay: 75,
    timezone: "Asia/Ashgabat",
    latitude: 40.022,
    longitude: 52.97,
  },
  {
    id: "beyneu",
    name: "Beyneu",
    city: "Beyneu",
    kind: "land",
    load: 54,
    capacityPerDay: 100,
    timezone: "Asia/Qyzylorda",
    latitude: 45.318,
    longitude: 55.198,
  },
];

export const seedBookings = [
  {
    id: "booking-01",
    portId: "aktau",
    userId: "user-carrier",
    date: today,
    slot: "08:00",
    purpose: "export",
    status: "confirmed",
  },
  {
    id: "booking-02",
    portId: "kuryk",
    userId: "user-shipper",
    date: today,
    slot: "14:00",
    purpose: "import",
    status: "confirmed",
  },
];

export const seedLessons = [
  {
    id: "lesson-01",
    title: "Registration and profile setup",
    description: "Create an account and fill in your transport profile in 3 minutes.",
    durationMinutes: 3,
    language: "ru",
    stage: 1,
  },
  {
    id: "lesson-02",
    title: "Reading port congestion",
    description: "Understand color codes and congestion to avoid waiting in line.",
    durationMinutes: 5,
    language: "ru",
    stage: 2,
  },
  {
    id: "lesson-03",
    title: "Freight Tinder",
    description: "Swipe loads, accept the best ones, and keep the route efficient.",
    durationMinutes: 4,
    language: "ru",
    stage: 3,
  },
  {
    id: "lesson-04",
    title: "Port booking",
    description: "Book a time slot like a table reservation and avoid chaos.",
    durationMinutes: 3,
    language: "ru",
    stage: 4,
  },
  {
    id: "lesson-05",
    title: "Carrier rating system",
    description: "See how delays, cancellations, reviews and eco metrics are scored.",
    durationMinutes: 6,
    language: "ru",
    stage: 5,
  },
  {
    id: "lesson-06",
    title: "First successful trip bonus",
    description: "Unlock platform bonuses after the first completed route.",
    durationMinutes: 2,
    language: "ru",
    stage: 6,
  },
];

export const seedTrajectories = [
  {
    id: "route-01",
    from: "Aktau",
    to: "Atyrau",
    mode: "truck",
    status: "free",
    load: 32,
    distance: 510,
    congestion: "low",
    note: "Good for empty backhaul picks.",
  },
  {
    id: "route-02",
    from: "Aktau",
    to: "Kuryk",
    mode: "sea",
    status: "busy",
    load: 86,
    distance: 72,
    congestion: "high",
    note: "Port queue is already growing.",
  },
  {
    id: "route-03",
    from: "Kuryk",
    to: "Baku",
    mode: "sea",
    status: "medium",
    load: 62,
    distance: 380,
    congestion: "medium",
    note: "Best window is early morning.",
  },
  {
    id: "route-04",
    from: "Beyneu",
    to: "Russia Border",
    mode: "truck",
    status: "medium",
    load: 54,
    distance: 410,
    congestion: "medium",
    note: "Watch border time slots.",
  },
  {
    id: "route-05",
    from: "Turkmenbashi",
    to: "Kuryk",
    mode: "sea",
    status: "free",
    load: 28,
    distance: 320,
    congestion: "low",
    note: "Nice corridor for return cargo.",
  },
];

export const seedRatingRules = [
  { key: "delays", label: "Delays", weight: -20, source: "Tracking history" },
  { key: "cancellations", label: "Cancellations", weight: -30, source: "Booking history" },
  { key: "eco", label: "Eco score", weight: 10, source: "Fuel and vehicle data" },
  { key: "reviews", label: "Sender reviews", weight: 15, source: "Post-trip feedback" },
  { key: "quality", label: "Shipment quality", weight: 20, source: "Damage and claims" },
];

export const seedAiPrompts = [
  {
    key: "map_forecast",
    title: "Port congestion forecast",
    category: "map",
    description: "Forecast congestion for ports and checkpoints and suggest a reroute.",
    template:
      "Location: {{locationName}}\nCurrent load: {{load}}%\nQueue: {{queue}} trucks\nWait: {{waitHours}} hours\nLanguage: {{language}}",
    instructions:
      `You are WEST's logistics AI. Write a concise forecast in the requested language. Mention the expected congestion change, the practical action a carrier should take, and keep the answer to 2 short sentences. ${promptStrictness}`,
    model: "o4-mini",
    active: true,
    updatedAt: "2026-06-11T08:00:00.000Z",
  },
  {
    key: "order_suggestion",
    title: "Order price suggestion",
    category: "order",
    description: "Recommend a realistic market rate for the shipment form.",
    template:
      "Route: {{from}} -> {{to}}\nCargo type: {{cargoType}}\nWeight: {{weight}} tons\nDeclared price: {{price}} KZT\nTransport: {{transport}}\nLanguage: {{language}}",
    instructions:
      `You are WEST's pricing analyst. Explain whether the price is under market, fair, or high. Give one practical recommendation for the shipper and one short reason for carriers. Keep it concise. ${promptStrictness}`,
    model: "o4-mini",
    active: true,
    updatedAt: "2026-06-11T08:00:00.000Z",
  },
  {
    key: "tinder_match",
    title: "Freight Tinder match",
    category: "tinder",
    description: "Explain why a cargo card matches the carrier profile.",
    template:
      "Route: {{from}} -> {{to}}\nCargo: {{cargoType}}\nWeight: {{weight}} kg\nPrice: {{price}} KZT\nTransport: {{transport}}\nRating: {{rating}}\nMatch score: {{matchScore}}\nLanguage: {{language}}",
    instructions:
      `You are WEST's matching engine. Explain the match in one short sentence and add 2 short bullet points with the strongest reasons. Use the requested language. ${promptStrictness}`,
    model: "o4-mini",
    active: true,
    updatedAt: "2026-06-11T08:00:00.000Z",
  },
  {
    key: "backhaul_match",
    title: "Backhaul cargo match",
    category: "backhaul",
    description: "Explain and rank return-trip cargo options.",
    template:
      "Route: {{from}} -> {{to}}\nFree capacity: {{capacity}} kg\nLanguage: {{language}}",
    instructions:
      `You are WEST's empty-truck hunter. Pick the best return-trip options, explain why they fit, and keep the answer focused on economics and route efficiency. ${promptStrictness}`,
    model: "o4-mini",
    active: true,
    updatedAt: "2026-06-11T08:00:00.000Z",
  },
  {
    key: "customs_analysis",
    title: "Customs document check",
    category: "customs",
    description: "Check the route and warn about missing customs documents.",
    template:
      "Route: {{route}}\nCargo type: {{cargoType}}\nDocument text: {{documents}}\nLanguage: {{language}}",
    instructions:
      `You are WEST's customs assistant. List the likely missing documents, any border risks, and one practical next step. Keep it concise and actionable. ${promptStrictness}`,
    model: "o4-mini",
    active: true,
    updatedAt: "2026-06-11T08:00:00.000Z",
  },
  {
    key: "dashboard_summary",
    title: "Daily logistics summary",
    category: "dashboard",
    description: "Summarize the daily system status for the akimat dashboard.",
    template:
      "Active users: {{activeUsers}}\nOpen freights: {{openFreights}}\nBusy ports: {{busyPorts}}\nAverage driver score: {{averageDriverScore}}\nMonthly revenue: {{revenue}}\nLanguage: {{language}}",
    instructions:
      `You are WEST's executive dashboard analyst. Write a short executive summary and a bullet list of 3 key actions for the akimat. Keep it crisp and professional. ${promptStrictness}`,
    model: "o4-mini",
    active: true,
    updatedAt: "2026-06-11T08:00:00.000Z",
  },
];

export const seedAiAnalyses = [
  {
    id: "ai-analysis-01",
    promptKey: "map_forecast",
    entityType: "port",
    entityId: "aktau",
    input: { locationName: "Aktau Port", load: 88, queue: 24, waitHours: 3.5, language: "ru" },
    summary: "Порт Ақтау перегреется до 95% загрузки примерно через 2 часа. Лучше уходить через Құрық или бронировать слот заранее.",
    bullets: ["Ожидается рост очереди", "Рекомендуется reroute через Kuryk", "Бронируйте слот до 12:00"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:05:00.000Z",
  },
  {
    id: "ai-analysis-02",
    promptKey: "map_forecast",
    entityType: "port",
    entityId: "kuryk",
    input: { locationName: "Kuryk Port", load: 45, queue: 8, waitHours: 1.0, language: "en" },
    summary: "Kuryk is stable right now, but the queue can rise by evening. It is the safer reroute for trucks heading away from Aktau.",
    bullets: ["Queue is moderate", "Evening demand may rise", "Safe reroute for trucks"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:10:00.000Z",
  },
  {
    id: "ai-analysis-03",
    promptKey: "order_suggestion",
    entityType: "shipment",
    entityId: "freight-01",
    input: { from: "Aktau", to: "Atyrau", cargoType: "Petrochemicals", weight: 18, price: 420000, transport: "truck", language: "ru" },
    summary: "Ставка выглядит рыночной и хорошо зайдёт флиту с актуальным плечом Aktau → Atyrau. Для ускорения матча можно поднять цену до 450K ₸.",
    bullets: ["Price is fair", "Raise bid slightly for faster acceptance", "Truck carriers will match quickly"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:15:00.000Z",
  },
  {
    id: "ai-analysis-04",
    promptKey: "order_suggestion",
    entityType: "shipment",
    entityId: "freight-04",
    input: { from: "Aktau Port", to: "Almaty", cargoType: "Refrigerated", weight: 22, price: 920000, transport: "truck", language: "en" },
    summary: "This order is premium and will attract only high-rated refrigerated carriers. The rate is above market, so it should fill fast.",
    bullets: ["Premium cargo", "High-rating carriers only", "Fast fill likely"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:20:00.000Z",
  },
  {
    id: "ai-analysis-05",
    promptKey: "tinder_match",
    entityType: "freight",
    entityId: "freight-02",
    input: { from: "Kuryk", to: "Baku", cargoType: "Container", weight: 24000, price: 380000, transport: "ship", rating: 4.6, matchScore: 88, language: "ru" },
    summary: "Маршрут и тип транспорта совпадают почти идеально. Это сильный матч для судов с текущим каспийским плечом.",
    bullets: ["Route fit is strong", "Ship transport is correct", "Good margin for the carrier"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:25:00.000Z",
  },
  {
    id: "ai-analysis-06",
    promptKey: "tinder_match",
    entityType: "freight",
    entityId: "freight-06",
    input: { from: "Turkmenbashi", to: "Kuryk", cargoType: "Sea container", weight: 30000, price: 540000, transport: "ship", rating: 4.7, matchScore: 92, language: "en" },
    summary: "Excellent match for a sea carrier: the route is aligned, the load is profitable, and the eco score is strong.",
    bullets: ["Aligned sea route", "High-profit load", "Eco-friendly option"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:30:00.000Z",
  },
  {
    id: "ai-analysis-07",
    promptKey: "backhaul_match",
    entityType: "route",
    entityId: "backhaul-baku-aktau",
    input: { from: "Baku", to: "Aktau", capacity: 18000, language: "ru" },
    summary: "На обратном плече выгоднее всего брать химпродукцию и контейнеры: они закрывают пустой пробег и дают высокий маржинальный рейс.",
    bullets: ["Best for chemicals", "Containers also fit", "Avoid empty return trip"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:35:00.000Z",
  },
  {
    id: "ai-analysis-08",
    promptKey: "backhaul_match",
    entityType: "route",
    entityId: "backhaul-turkmenbashi-kuryk",
    input: { from: "Turkmenbashi", to: "Kuryk", capacity: 22000, language: "en" },
    summary: "This return route is ideal for containers and fertilizers because the corridor is already active and the mileage stays efficient.",
    bullets: ["Good corridor activity", "Containers are the safest fit", "Strong backhaul margin"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:40:00.000Z",
  },
  {
    id: "ai-analysis-09",
    promptKey: "customs_analysis",
    entityType: "route",
    entityId: "KZ-TM-AZ",
    input: { route: "KZ-TM-AZ", cargoType: "Containers", documents: "CMR, invoice, packing list", language: "ru" },
    summary: "Для этого маршрута не хватает сертификата происхождения и транзитной декларации. Проверьте документы до прибытия на границу.",
    bullets: ["Certificate of Origin missing", "Transit declaration required", "Prepare docs before border"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:45:00.000Z",
  },
  {
    id: "ai-analysis-10",
    promptKey: "dashboard_summary",
    entityType: "dashboard",
    entityId: "daily-summary",
    input: { activeUsers: 186, openFreights: 42, busyPorts: 2, averageDriverScore: 87, revenue: 12450000, language: "en" },
    summary: "The system is healthy: open cargo remains high, but the busiest ports are still under control. The main action is to push more backhaul matches into the evening window.",
    bullets: ["Queue hotspots remain manageable", "Backhaul matching should be prioritized", "Evening slots need more bookings"],
    source: "mock",
    model: "o4-mini",
    createdAt: "2026-06-11T08:50:00.000Z",
  },
];
